# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d332d0477f29224698653358c9e507babd384f5d0324a24b64812a1b02274baba865f355597e22254d24d22bff279e8b533f100cec1088167be45ddef8f0960d

test:
  secret_key_base: 51874c70fac24a99c37242b83ac2db66c90f297d1d2c7ea4349a16ea0cd14a4f83185c2167bc211db31bb0f9f4598ba975cba19f7b9c4a14491fdcad9897fb37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
